/* GENERATED by tools/build.py - do not edit; edit sw.template.js. */
/* sw.js — GENERATED. Edit sw.template.js, then run tools/build.py.
 *
 * Precache-first, freshness owned by the LIFECYCLE and never by the fetch handler.
 * GUIDE §7.2, §7.5, §7.10, §7.11.
 */
'use strict';

/* GUIDE §7.10 — the cache name is a sha256 over every precached byte. That makes an
   asset change INTO a worker-script change, which is the only thing that triggers a
   reinstall. A hand-bumped constant can be forgotten, and a forgotten bump is a
   byte-identical worker, no handover at all, and a symptom indistinguishable from a
   caching bug. A hash cannot be forgotten. */
var CACHE  = 'notes-3e60da1a997d';
var PREFIX = CACHE.replace(/-[0-9a-f]{12}$/, '');
/* GUIDE §7.10 — emitted from the build's own write log, never hand-maintained: a
   hand-kept array drifts the moment anyone adds a file, and the drift is invisible
   until someone is offline. */
var ASSETS = [
  "./config.js",
  "./css/base.css",
  "./css/editor.css",
  "./css/layout.css",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./js/adapters/net.js",
  "./js/adapters/store.js",
  "./js/data/api.js",
  "./js/data/auth.js",
  "./js/data/sync.js",
  "./js/editor/caret.js",
  "./js/editor/input.js",
  "./js/editor/render.js",
  "./js/main.js",
  "./js/model/doc.js",
  "./js/model/schema.js",
  "./js/ui/diag.js",
  "./js/ui/footer.js",
  "./js/ui/layout.js",
  "./js/ui/panes.js",
  "./js/ui/sidebar.js",
  "./manifest.webmanifest",
  "./update.js"
];
var NET_TIMEOUT_MS = 2500;

var SCOPE     = self.registration.scope;
var SHELL_URL = new URL('./index.html', SCOPE).href;
var PRECACHED = new Set(ASSETS.map(function (a) { return new URL(a, SCOPE).href; }));
PRECACHED.add(new URL('./', SCOPE).href);

/* GUIDE §7.10 — addAll is all-or-nothing. One 404 fails the install LOUDLY while you
   are online, instead of leaving a half-cached app that works online and breaks
   offline — the one state nobody tests.
   GUIDE §7.5 — deliberately NO skipWaiting() here. We wait to be told, at the moment
   the page has already confirmed it is idle. Activating on install would leave the
   OLD page running on the NEW cache for however long the idle gate takes, which is
   the mixed-build bug arrived at through the lifecycle instead of the fetch handler. */
self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); }));
});

/* The precache is replaced ATOMICALLY. Drop only THIS channel's old caches — never
   another channel's, never another project's. On a *.github.io origin every repo that
   account publishes shares one CacheStorage (GUIDE §8.1). */
self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        if (k !== CACHE && k.indexOf(PREFIX + '-') === 0) return caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('message', function (e) {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});

/* GUIDE §7.11 — AbortController, so the timeout actually cancels the request. A bare
   setTimeout rejects the promise and leaves the fetch in flight; combined with a
   .catch fallback that issues a second request, a flaky link piles them up. */
function fromNetwork(req) {
  return new Promise(function (resolve, reject) {
    var ac = (typeof AbortController !== 'undefined') ? new AbortController() : null;
    var bail = setTimeout(function () {
      if (ac) { try { ac.abort(); } catch (e) {} }
      reject(new Error('timeout'));
    }, NET_TIMEOUT_MS);
    fetch(req, ac ? { signal: ac.signal } : undefined).then(function (res) {
      clearTimeout(bail);
      // Never accept an opaque or failed response into a cache path: status 0, an
      // unreadable body, padded quota, and no way to tell success from failure.
      if (!res || !res.ok || res.type === 'opaque') { reject(new Error('bad')); return; }
      resolve(res);
    })['catch'](function (err) { clearTimeout(bail); reject(err); });
  });
}

function offline() { return new Response('', { status: 504, statusText: 'offline' }); }

self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET') return;

  var url;
  try { url = new URL(req.url); } catch (e) { return; }
  // GUIDE §7.11 — bail BEFORE respondWith, so cross-origin requests go to the network
  // untouched rather than being mediated by us. Supabase calls take this path.
  if (url.origin !== self.location.origin) return;

  /* GUIDE §7.2 — every same-origin request resolves from ONE build. A navigation
     ALWAYS gets the precached shell: never a race, because a slow navigation falling
     back to a cached shell while its sibling scripts arrive fresh over the network is
     exactly how two builds end up on screen at once. Neither build is broken; the
     PAIR is — and because the files mutually assume each other, the result is
     plausible wrong behaviour rather than an exception. Nothing throws. */
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.open(CACHE)
        .then(function (c) { return c.match(SHELL_URL); })
        .then(function (hit) { return hit || fetch(req); })
    );
    return;
  }

  // A precached URL comes from the precache, ALWAYS. No freshness decision is ever
  // made per request — that is the worker lifecycle's job, driven by update.js
  // calling update() on every foreground.
  if (PRECACHED.has(url.href)) {
    event.respondWith(
      caches.open(CACHE)
        .then(function (c) { return c.match(url.href); })
        .then(function (hit) { return hit || fromNetwork(req)['catch'](offline); })
    );
    return;
  }

  event.respondWith(
    fromNetwork(req)['catch'](function () {
      return caches.match(req).then(function (hit) { return hit || offline(); });
    })
  );
});
