#!/usr/bin/env python3
"""Stamp the service worker. The ONLY build step in this project.

This does not transpile, bundle or minify anything. Every source file in the repo is
served byte-for-byte as written. All this does is fill two placeholders in
sw.template.js, because of an unavoidable fact:

    A browser reinstalls a service worker only when the worker script's own bytes
    differ from the installed copy.

So an asset change has to BECOME a script change, or the device keeps serving the old
build forever (GUIDE §7.10). The alternative is a hand-bumped version constant, which
can be forgotten — and a forgotten bump produces a symptom indistinguishable from a
caching bug. A content hash cannot be forgotten.

Standard library only. No dependencies, here or anywhere.
"""
import hashlib, json, os, sys, signal
try: signal.signal(signal.SIGPIPE, signal.SIG_DFL)
except Exception: pass

APP = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'notes')
APP = os.path.normpath(APP)
PREFIX = 'notes'

SKIP_DIRS = {'test', 'node_modules', '.git'}
SKIP_FILES = {'sw.js', 'sw.template.js', '.DS_Store'}
SKIP_EXT = {'.md', '.mjs', '.py'}


def collect():
    out = []
    for root, dirs, files in os.walk(APP):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith('.')]
        for f in sorted(files):
            if f.startswith('.') or f in SKIP_FILES or os.path.splitext(f)[1] in SKIP_EXT:
                continue
            rel = os.path.relpath(os.path.join(root, f), APP).replace(os.sep, '/')
            out.append('./' + rel)
    return sorted(out)


def main():
    assets = collect()
    if not assets:
        sys.exit('build: refusing to emit an empty precache')

    # GUIDE §7.10 — hash from DISK, every run, AFTER any in-place patch. Patching a
    # published asset without re-deriving this leaves the worker byte-identical: no
    # update is detected, no install happens, and a precache-first worker serves its
    # existing copies indefinitely. The fix reaches first-time visitors over the
    # network and never reaches the installed devices it was written for.
    digest = hashlib.sha256()
    for rel in assets:
        digest.update(rel.encode())
        with open(os.path.join(APP, rel[2:]), 'rb') as fh:
            digest.update(fh.read())
    cache_name = PREFIX + '-' + digest.hexdigest()[:12]

    with open(os.path.join(APP, 'sw.template.js'), encoding='utf-8') as fh:
        tpl = fh.read()
    sw = (tpl.replace('__CACHE_NAME__', cache_name)
             .replace('__ASSETS__', json.dumps(assets, indent=2)))
    sw = '/* GENERATED by tools/build.py - do not edit; edit sw.template.js. */\n' + sw

    with open(os.path.join(APP, 'sw.js'), 'w', encoding='utf-8') as fh:
        fh.write(sw)

    # GUIDE §8.3 — Pages runs Jekyll over a branch by default and silently drops
    # leading-underscore paths. No error anywhere: green deploy, 404 request, and an
    # all-or-nothing precache that can never install.
    open(os.path.join(APP, '..', '.nojekyll'), 'a').close()

    print(cache_name, '·', len(assets), 'assets')
    for a in assets:
        print('   ', a)


if __name__ == '__main__':
    main()
